:sectnumlevels: 5
:toclevels: 5
:sectnums:
:source-highlighter: coderay

= *Device API*
:toc: left

== *Overview*
- Data Structure.
- Thing Service - Hub Service interface.

== *Revision history*

[cols="1,1,1,3", options="header"]
|===
|*Date*
|*PIC*
|*Version*
|*Description*

|08/02/2022
|Nga Le
|1.0
|Initial version.

|11/02/2022
|Nga Le
|1.1
|Add and update device APIs.

|===

== *Data Structure*

=== *Device Structure*:
----
{
  "id": <string>,
  "name":<string>,
  "status": <int>,
  "mac": <string>,
  "protocol": <string>,
  "power_source": <int>,
  "nexthop_id": <string>,
  "is_virtual":<boolean>,
  "infos": {
    "KEY": VALUE, //any primitive types and string
  },
  "end_points": [
    <end_point_structure>
  ],
  "binding": [
    <binding_structure>
  ],
  "grouping": [
    <grouping_structure>
  ]
}
----

=== *Binding Structure*:
----
{
  "source_ep": <int>,
  "dest_ep": <int>,
  "dest_id": <string>,
  "is_group": <boolean>,
  "clus_id": <int>
}
----

=== *Grouping Structure*:
----
{
  "group_id": <string>,
  "device_id": <string>,
  "ep": <int>
}
----

=== *Endpoint Structure*:
----
{
  "id": <string>,
  "type": <int>,
  "name": <string>,
  "is_controllable": <boolen>
  "attributes": {
    "KEY": VALUE, //any primitive types and string
  },
  "settings":[
    <setting_1>,
    <setting_2>,
    <setting_3>
  ],
  "user_pins": [
    <user_pin_1>,
    <user_pin_2>,
    <user_pin_3>
  ]
}
----

=== *Setting Structure*:
----
{
  "name": <string>,
  "value": <int>,
  "min": <int>,
  "max": <int>,
  "step": <int>
}
----

=== *User Pincode Structure*:
----
{
  "id":<string>,
  "pin":<string>
}
----

=== *Defined Enums*:

==== *Device Status*:
----
OK = 0,
Error = 1
----

==== *Power Source*:
----
AC = 0,
Battery = 1
----

=== *Example Device Model*:
----
{
  "binding": [],
  "grouping": [],
  "end_points": [
    {
      "attributes": {
        "color.color_temperature": 0,
        "color.hue": 0,
        "color.level": 100,
        "color.saturation": 100,
        "on_off.value": true
      },
      "id": "11",
      "is_controllable": true,
      "name": "color_switch",
      "settings": [],
      "type": 3
    }
  ],
  "id": "PHILLIP_HUE_001788010386CDDE",
  "infos": {
    "commit_fw_version": "",
    "commit_hw_version": "",
    "fw_version": "2",
    "hw_version": "1",
    "manufacturer": "",
    "manufacturer_id": "",
    "product_id": ""
  },
  "is_sleepy": false,
  "is_virtual": false,
  "mac": "ZIB_001788010386CDDE",
  "name": "name_unknown",
  "nexthop_id": "id_unknown",
  "nwkid": 43015,
  "power_source": 0,
  "protocol": "zib",
  "status": 0
}
----

== *Thing Service - Hub Service interface*

=== *Register Device*:

==== *Sequence Diagram*:

[plantuml, "register_device_sequence", png]
----
@startuml
autonumber
App --> ThingService: Request Join Device
ThingService --> HubService: Request Join Device
HubService -> HubService: Wait for new device
alt successful case
HubService --> ThingService: Register Device Request
ThingService -> ThingService: Register Device
ThingService --> HubService: Register Device Response
HubService -> HubService: Store Device Info
HubService --> ThingService: Device Joined
ThingService --> App: New Device
else timeout case
autonumber 4 1
HubService --> ThingService: Request Timeout
ThingService --> App: Request Timeout
end
@enduml
----

*Notes*:

- In the scope of this document, we only focus into the *successful case*.

==== *Message Interface*:

*Request Join*:

- *Topic*: _ts/event/HUB_ID_

- *Payload*:

[source,json]
----
{
  "name": "ts.hub.iot.device.join.requested",
  "scope": "device",
  "source": "ts",
  "home_id": "HOME_ID",
  "user_id": "",
  "id": "MESSAGE_ID",
  "auth_token": "AUTH_TOKEN",
  "parent_id": "",
  "client_id": "TS_ID",
  "created_time": 1584501452048,
  "data": {
    "protocol": <string>
    "data": {
      //any required data for adding new device
    }
  }
}
----

- *Notes*: The specific *protocol* is mandatory. The *data* is optional for addition informations.

*Join Timeout*:

- *Topic*: _hub/event/HUB_ID_
- *Payload*:

[source,json]
----
{
  "name": "hub.ts.iot.device.join.timeout",
  "scope": "device",
  "source": "hub",
  "home_id": "HOME_ID",
  "user_id": "",
  "id": "MESSAGE_ID",
  "auth_token": "AUTH_TOKEN",
  "parent_id": "",
  "client_id": "HUB_ID",
  "created_time": 1584501452048,
  "data": {
    "protocol": <string>
  }
}
----

- *Notes*: The specific *protocol* is mandatory.

*Register Device Request*:

- *Topic*: _hub/event/HUB_ID_

- *Payload*:

[source,json]
----
{
  "name": "hub.ts.iot.device.register.requested",
  "scope": "device",
  "source": "hub",
  "home_id": "HOME_ID",
  "user_id": "",
  "id": "MESSAGE_ID",
  "auth_token": "AUTH_TOKEN",
  "parent_id": "",
  "client_id": "HUB_ID",
  "created_time": 1584501452048,
  "data": {
    <device_structure>
  }
}
----

- *Notes*: In the device structure, the *id* field can be an empty string or same as *mac* field.

*Register Device Response*:

- *Topic*: _ts/event/HUB_ID_

- *Payload*:

[source,json]
----
{
  "name": "ts.hub.iot.device.register.responded",
  "scope": "device",
  "source": "ts",
  "home_id": "HOME_ID",
  "user_id": "",
  "id": "MESSAGE_ID",
  "auth_token": "AUTH_TOKEN",
  "parent_id": "",
  "client_id": "TS_ID",
  "created_time": 1584501452048,
  "data": {
    "error": {
      "code": <int>,
      "message": <string>
    },
    "data": <device_structure>
  }
}
----

*Device Joined*:

- *Topic*: _hub/event/HUB_ID_

- *Payload*:

[source,json]
----
{
  "name": "broadcast.iot.device.joined",
  "scope": "device",
  "source": "hub",
  "home_id": "HOME_ID",
  "user_id": "",
  "id": "MESSAGE_ID",
  "auth_token": "AUTH_TOKEN",
  "parent_id": "",
  "client_id": "HUB_ID",
  "created_time": 1584501452048,
  "data": {
    <device_structure>
  }
}
----

=== *Remove Device*:

==== *Sequence Diagram*:

[plantuml, "remove_device_sequence", png]
----
@startuml
autonumber
App --> ThingService: Remove Request
ThingService --> HubService: Remove Request
HubService -> HubService: Remove Device
alt successful case
HubService --> ThingService: Device Left Request
ThingService -> ThingService: Remove Device
ThingService --> HubService: Device Left Response
ThingService --> App: Notify Device Left
else timeout case
App -> App: Remove Timeout
end
@enduml
----

==== *Message Interface*:

*Request Remove*:

- *Topic*: _ts/event/HUB_ID_

- *Payload*:

[source,json]
----
{
  "name": "ts.hub.iot.device.remove.requested",
  "scope": "device",
  "source": "ts",
  "home_id": "HOME_ID",
  "user_id": "",
  "id": "MESSAGE_ID",
  "auth_token": "AUTH_TOKEN",
  "parent_id": "",
  "client_id": "TS_ID",
  "created_time": 1584501452048,
  "data": {
    <device_structure>
  }
}
----

*Device Left Request*:

- *Topic*: _hub/event/HUB_ID_

- *Payload*:

[source,json]
----
{
  "name": "hub.ts.iot.device.left.requested",
  "scope": "device",
  "source": "hub",
  "home_id": "HOME_ID",
  "user_id": "",
  "id": "MESSAGE_ID",
  "auth_token": "AUTH_TOKEN",
  "parent_id": "",
  "client_id": "HUB_ID",
  "created_time": 1584501452048,
  "data": {
    <device_structure>
  }
}
----

*Device Left Response*:

- *Topic*: _ts/event/HUB_ID_

- *Payload*:

[source,json]
----
{
  "name": "ts.hub.iot.device.left.responded",
  "scope": "device",
  "source": "ts",
  "home_id": "HOME_ID",
  "user_id": "",
  "id": "MESSAGE_ID",
  "auth_token": "AUTH_TOKEN",
  "parent_id": "",
  "client_id": "TS_ID",
  "created_time": 1584501452048,
  "data": {
    "error": {
      "code": <int>,
      "message": <string>
    },
    "data": <device_structure>
  }
}
----

*Device Left*:

- *Topic*: _hub/event/HUB_ID_

- *Payload*:

[source,json]
----
{
  "name": "broadcast.iot.device.left",
  "scope": "device",
  "source": "hub",
  "home_id": "HOME_ID",
  "user_id": "",
  "id": "MESSAGE_ID",
  "auth_token": "AUTH_TOKEN",
  "parent_id": "",
  "client_id": "HUB_ID",
  "created_time": 1584501452048,
  "data": {
    <device_structure>
  }
}
----

=== *Device Report*:

==== *Message Interface*:

*Report Message*:

- *Topic*: _hub/event/HUB_ID_

- *Payload*:

[source,json]
----
{
  "name": "broadcast.iot.device.reported",
  "scope": "device",
  "source": "hub",
  "home_id": "HOME_ID",
  "user_id": "",
  "id": "MESSAGE_ID",
  "auth_token": "AUTH_TOKEN",
  "parent_id": "",
  "client_id": "HUB_ID",
  "created_time": 1584501452048,
  "data": {
    <device_structure>
  }
}
----

=== *Device State Change*:

==== *Sequence Diagram*:

[plantuml, "device_state_change_sequence", png]
----
@startuml
autonumber
App --> ThingService: Change Device State
ThingService --> HubService: Request State Change
HubService -> HubService: Change Device State
HubService --> ThingService: Device State Change
ThingService -> ThingService: Update Device State
ThingService --> App: Notify Device State
@enduml
----

==== *Message Interface*:

*Request State Change*:

- *Topic*: _ts/event/HUB_ID_

- *Payload*:

[source,json]
----
{
  "name": "ts.hub.iot.devices.state.changed",
  "scope": "device",
  "source": "ts",
  "home_id": "HOME_ID",
  "user_id": "",
  "id": "MESSAGE_ID",
  "auth_token": "AUTH_TOKEN",
  "parent_id": "",
  "client_id": "TS_ID",
  "created_time": 1584501452048,
  "data": {
    "devices": [
      <device_structure_1>,
      <device_structure_2>,
      <device_structure_3>
    ]
  }
}
----

- *Notes*: The state change request only contains updated states.

*Device State Change*:

- *Topic*: _hub/event/HUB_ID_

- *Payload*:

[source,json]
----
{
  "name": "broadcast.iot.device.state.changed",
  "scope": "device",
  "source": "hub",
  "home_id": "HOME_ID",
  "user_id": "",
  "id": "MESSAGE_ID",
  "auth_token": "AUTH_TOKEN",
  "parent_id": "",
  "client_id": "HUB_ID",
  "created_time": 1584501452048,
  "data": {
    <device_structure>
  }
}
----

- *Notes*: The state change broadcast need to contain full device states.

=== *Request Device List*:

==== *Message Interface*:

*Device List Request*:

- *Topic*: _ts/event/HUB_ID_

- *Payload*:

[source,json]
----
{
  "name": "ts.hub.iot.devices.list.requested",
  "scope": "device",
  "source": "ts",
  "home_id": "HOME_ID",
  "user_id": "",
  "id": "MESSAGE_ID",
  "auth_token": "AUTH_TOKEN",
  "parent_id": "",
  "client_id": "TS_ID",
  "created_time": 1584501452048,
  "data": <NULL>
}
----

*Device List Response*:

- *Topic*: _hub/event/HUB_ID_

- *Payload*:

[source,json]
----
{
  "name": "hub.ts.iot.devices.list.responded",
  "scope": "device",
  "source": "hub",
  "home_id": "HOME_ID",
  "user_id": "",
  "id": "MESSAGE_ID",
  "auth_token": "AUTH_TOKEN",
  "parent_id": "",
  "client_id": "HUB_ID",
  "created_time": 1584501452048,
  "data": {
    "devices": [
      <device_structure_1>,
      <device_structure_2>,
      <device_structure_3>
    ]
  }
}
----

*Device List Notify*:

- *Topic*: _hub/event/HUB_ID_

- *Payload*:

[source,json]
----
{
  "name": "broadcast.iot.devices.list.changed",
  "scope": "device",
  "source": "hub",
  "home_id": "HOME_ID",
  "user_id": "",
  "id": "MESSAGE_ID",
  "auth_token": "AUTH_TOKEN",
  "parent_id": "",
  "client_id": "HUB_ID",
  "created_time": 1584501452048,
  "data": {
    "devices": [
      <device_structure_1>,
      <device_structure_2>,
      <device_structure_3>
    ]
  }
}
----

=== *Device Name Setting*:

==== *Sequence Diagram*:

[plantuml, "device_name_setting_sequence", png]
----
@startuml
autonumber
App --> ThingService: Change Device Name
ThingService --> HubService: Name Change Request
HubService -> HubService: Update Device Name
HubService --> ThingService: Name Change Response
ThingService -> ThingService: Update Device Name
ThingService --> App: Notify Device Update
@enduml
----

==== *Message Interface*:

*Change Name Request*

- *Topic*: _ts/event/HUB_ID_

- *Payload*:

[source,json]
----
{
  "name": "ts.hub.iot.device.name.requested",
  "scope": "device",
  "source": "ts",
  "home_id": "HOME_ID",
  "user_id": "",
  "id": "MESSAGE_ID",
  "auth_token": "AUTH_TOKEN",
  "parent_id": "",
  "client_id": "TS_ID",
  "created_time": 1584501452048,
  "data": {
    <device_structure>
  }
}
----

*Change Name Response*:

- *Topic*: _hub/event/HUB_ID_

- *Payload*:

[source,json]
----
{
  "name": "hub.ts.iot.device.name.responded",
  "scope": "device",
  "source": "hub",
  "home_id": "HOME_ID",
  "user_id": "",
  "id": "MESSAGE_ID",
  "auth_token": "AUTH_TOKEN",
  "parent_id": "",
  "client_id": "HUB_ID",
  "created_time": 1584501452048,
  "data": {
    "error": {
      "code": <int>,
      "message": <string>
    },
    "data": <device_structure>
  }
}
----

*Device Info Broadcast*:

- *Topic*: _hub/event/HOME_ID_

- *Payload*:

[source,json]
----
{
  "name": "broadcast.iot.device.info.changed",
  "scope": "device",
  "source": "hub",
  "home_id": "HOME_ID",
  "user_id": "",
  "id": "MESSAGE_ID",
  "auth_token": "AUTH_TOKEN",
  "parent_id": "",
  "client_id": "HUB_ID",
  "created_time": 1584501452048,
  "data": {
    <device_structure>
  }
}
----

=== *Device Basic Setting*:

==== *Sequence Diagram*:

[plantuml, "device_basic_setting_sequence", png]
----
@startuml
autonumber
App --> ThingService: Change Device Setting
ThingService --> HubService: Basic Setting Request
HubService -> HubService: Update Basic Setting
alt successful case
HubService --> ThingService: Basic Setting Response
ThingService -> ThingService: Update Device Setting
ThingService --> App: Notify Device Update
else fail case
autonumber 4 1
HubService --> ThingService: Basic Setting Failed
ThingService --> App: Notify Setting Failed
end
@enduml
----

==== *Message Interface*:

*Basic Setting Request*:

- *Topic*: _ts/event/HUB_ID_

- *Payload*:

[source,json]
----
{
  "name": "ts.hub.iot.device.basic_setting.requested",
  "scope": "device",
  "source": "ts",
  "home_id": "HOME_ID",
  "user_id": "",
  "id": "MESSAGE_ID",
  "auth_token": "AUTH_TOKEN",
  "parent_id": "",
  "client_id": "TS_ID",
  "created_time": 1584501452048,
  "data": {
    <device_structure>
  }
}
----

- *Notes*: The basic setting request only contains updated settings.

*Basic Setting Response*:

- *Topic*: _hub/event/HUB_ID_

- *Payload*:

[source,json]
----
{
  "name": "hub.ts.iot.device.basic_setting.responded",
  "scope": "device",
  "source": "hub",
  "home_id": "HOME_ID",
  "user_id": "",
  "id": "MESSAGE_ID",
  "auth_token": "AUTH_TOKEN",
  "parent_id": "",
  "client_id": "HUB_ID",
  "created_time": 1584501452048,
  "data": {
    "error": {
      "code": <int>,
      "message": <string>
    },
    "data": <device_structure>
  }
}
----

- *Notes*: The basic setting response must contains all settings.

*Device Info Broadcast*:

- *Topic*: _hub/event/HOME_ID_

- *Payload*:

[source,json]
----
{
  "name": "broadcast.iot.device.info.changed",
  "scope": "device",
  "source": "hub",
  "home_id": "HOME_ID",
  "user_id": "",
  "id": "MESSAGE_ID",
  "auth_token": "AUTH_TOKEN",
  "parent_id": "",
  "client_id": "HUB_ID",
  "created_time": 1584501452048,
  "data": {
    <device_structure>
  }
}
----

=== *Device Advance Setting*:

==== *Sequence Diagram*:

[plantuml, "device_advanced_setting_sequence", png]
----
@startuml
autonumber
App --> ThingService: New Advanced Setting
ThingService --> HubService: Advanced Setting Request
HubService -> HubService: Update Advanced Setting
alt successful case
HubService -> HubService: Store Advanced Setting
HubService --> ThingService: Advanced Setting Response
ThingService -> ThingService: Update Device Setting
ThingService --> App: Notify Device Update
else fail case
autonumber 4 1
HubService --> ThingService: Advanced Setting Failed
ThingService --> App: Notify Setting Failed
end
@enduml
----

==== *Message Interface*:

*Advanced Setting Request*:

- *Topic*: _ts/event/HUB_ID_

- *Payload*:

[source,json]
----
{
  "name": "ts.hub.iot.device.advanced_setting.requested",
  "scope": "device",
  "source": "ts",
  "home_id": "HOME_ID",
  "user_id": "",
  "id": "MESSAGE_ID",
  "auth_token": "AUTH_TOKEN",
  "parent_id": "",
  "client_id": "TS_ID",
  "created_time": 1584501452048,
  "data": {
    <device_structure>
  }
}
----

- *Notes*: The advanced setting request will contains a new advanced setting.

*Advanced Setting Response*:

- *Topic*: _hub/event/HUB_ID_

- *Payload*:

[source,json]
----
{
  "name": "hub.ts.iot.device.advanced_setting.responded",
  "scope": "device",
  "source": "hub",
  "home_id": "HOME_ID",
  "user_id": "",
  "id": "MESSAGE_ID",
  "auth_token": "AUTH_TOKEN",
  "parent_id": "",
  "client_id": "HUB_ID",
  "created_time": 1584501452048,
  "data": {
    "error": {
      "code": <int>,
      "message": <string>
    },
    "data": <device_structure>
  }
}
----

- *Notes*: The advanced setting response must contains all settings.

*Device Info Broadcast*:

- *Topic*: _hub/event/HOME_ID_

- *Payload*:

[source,json]
----
{
  "name": "broadcast.iot.device.info.changed",
  "scope": "device",
  "source": "hub",
  "home_id": "HOME_ID",
  "user_id": "",
  "id": "MESSAGE_ID",
  "auth_token": "AUTH_TOKEN",
  "parent_id": "",
  "client_id": "HUB_ID",
  "created_time": 1584501452048,
  "data": {
    <device_structure>
  }
}
----

=== *Device Binding Setting*:
- TBD

=== *Device Grouping Setting*:
- TBD

=== *Device Replace Setting*:
- TBD

