:sectnumlevels: 5
:toclevels: 5
:sectnums:
:source-highlighter: coderay

= *Scene API*
:toc: left

== *Overview*
- Data Structure.
- Thing Server - App interface.

== *Revision history*

[cols="1,1,1,3", options="header"]
|===
|*Date*
|*PIC*
|*Version*
|*Description*

|09/04/2022
|Nga Le
|1.0
|Initial version.

|12/04/2022
|Nga Le
|1.1
|Update data structure.

|===

== *Data Structure*

- *Reference*: xref:common/scene_model.adoc[]

== *Thing Server - App interface*

=== *Create Scene*:

==== *Message Interface*:

*Create Request*:

- *Subject*: _app.event.THING_SERVER_ID_

- *Payload*:

[source,json]
----
{
  "name": "app.scene.info.created",
  "scope": "scene",
  "source": "app",
  "home_id": "THING_SERVER_ID",
  "user_id": "",
  "id": "MESSAGE_ID",
  "auth_token": "AUTH_TOKEN",
  "parent_id": "",
  "client_id": "APP_ID",
  "created_time": 1584501452048,
  "data": {
    <scene_structure>
  }
}
----

*Create Notify*:

- *Subject*: _cs.event.THING_SERVER_ID_

- *Payload*:

[source,json]
----
{
  "name": "cs.scene.info.created",
  "scope": "scene",
  "source": "cs",
  "home_id": "THING_SERVER_ID",
  "user_id": "",
  "id": "MESSAGE_ID",
  "auth_token": "AUTH_TOKEN",
  "parent_id": "",
  "client_id": "TS_ID",
  "created_time": 1584501452048,
  "data": {
    <scene_structure>
  }
}
----

*Error Response*:

- *Subject*: _cs.event.APP_ID_

- *Payload*:

[source,json]
----
{
  "name": "cs.error.responded",
  "scope": "scene",
  "source": "cs",
  "home_id": "THING_SERVER_ID",
  "user_id": "",
  "id": "MESSAGE_ID",
  "auth_token": "AUTH_TOKEN",
  "parent_id": "",
  "client_id": "THING_SERVER_ID",
  "created_time": 1584501452048,
  "data": {
    "code": <int>,
    "message": <string>
  }
}
----

=== *Scene Update*:

==== *Message Interface*:

*Update Request*:

- *Subject*: _app.event.THING_SERVER_ID_

- *Payload*:

[source,json]
----
{
  "name": "app.scene.info.updated",
  "scope": "scene",
  "source": "app",
  "home_id": "THING_SERVER_ID",
  "user_id": "",
  "id": "MESSAGE_ID",
  "auth_token": "AUTH_TOKEN",
  "parent_id": "",
  "client_id": "APP_ID",
  "created_time": 1584501452048,
  "data": {
    <scene_structure>
  }
}
----

*Update Notify*:

- *Subject*: _cs.event.THING_SERVER_ID_

- *Payload*:

[source,json]
----
{
  "name": "cs.scene.info.updated",
  "scope": "scene",
  "source": "cs",
  "home_id": "THING_SERVER_ID",
  "user_id": "",
  "id": "MESSAGE_ID",
  "auth_token": "AUTH_TOKEN",
  "parent_id": "",
  "client_id": "THING_SERVER_ID",
  "created_time": 1584501452048,
  "data": {
    <scene_structure>
  }
}
----

=== *Scene Delete*:

==== *Message Interface*:

*Delete Request*:

- *Subject*: _app.event.THING_SERVER_ID_

- *Payload*:

[source,json]
----
{
  "name": "app.scene.info.deleted",
  "scope": "scene",
  "source": "app",
  "home_id": "THING_SERVER_ID",
  "user_id": "",
  "id": "MESSAGE_ID",
  "auth_token": "AUTH_TOKEN",
  "parent_id": "",
  "client_id": "APP_ID",
  "created_time": 1584501452048,
  "data": {
    <scene_structure>
  }
}
----

*Delete Notify*:

- *Subject*: _cs.event.THING_SERVER_ID_

- *Payload*:

[source,json]
----
{
  "name": "cs.scene.info.deleted",
  "scope": "scene",
  "source": "cs",
  "home_id": "THING_SERVER_ID",
  "user_id": "",
  "id": "MESSAGE_ID",
  "auth_token": "AUTH_TOKEN",
  "parent_id": "",
  "client_id": "THING_SERVER_ID",
  "created_time": 1584501452048,
  "data": {
    <scene_structure>
  }
}
----

=== *Scene List*:

==== *Message Interface*:

*Scene List Request*:

- *Subject*: _app.event.THING_SERVER_ID_

- *Payload*:

[source,json]
----
{
  "name": "app.scene.list.requested",
  "scope": "scene",
  "source": "app",
  "home_id": "THING_SERVER_ID",
  "user_id": "",
  "id": "MESSAGE_ID",
  "auth_token": "AUTH_TOKEN",
  "parent_id": "",
  "client_id": "APP_ID",
  "created_time": 1584501452048,
  "data": {
    "limit": <int>,
    "offset": <int>
  }
}
----

*Scene List Response*:

- *Subject*: _cs.event.APP_ID_

- *Payload*:

[source,json]
----
{
  "name": "cs.scene.list.responded",
  "scope": "scene",
  "source": "cs",
  "home_id": "THING_SERVER_ID",
  "user_id": "",
  "id": "MESSAGE_ID",
  "auth_token": "AUTH_TOKEN",
  "parent_id": "",
  "client_id": "THING_SERVER_ID",
  "created_time": 1584501452048,
  "data": {
    "limit": <int>,
    "offset": <int>,
    "scenes": [
      <scene_structure>,
      <scene_structure>,
      <scene_structure>
    ]
  }
}
----

=== *Scene Trigger*:

==== *Message Interface*:

*Trigger Request*:

- *Subject*: _app.event.THING_SERVER_ID_

- *Payload*:

[source,json]
----
{
  "name": "app.scene.info.triggered",
  "scope": "scene",
  "source": "app",
  "home_id": "THING_SERVER_ID",
  "user_id": "",
  "id": "MESSAGE_ID",
  "auth_token": "AUTH_TOKEN",
  "parent_id": "",
  "client_id": "APP_ID",
  "created_time": 1584501452048,
  "data": {
    "scenes": [
      <string>,
      <string>,
      <string>
    ]
  }
}
----

*Trigger Response*:

- *TBD*
