:sectnumlevels: 5
:toclevels: 5
:sectnums:
:source-highlighter: coderay

= *Permission Service*
:toc: left

== *Overview*
- System Overview.
- Permission APIs.

== *Revision history*

[cols="1,1,1,3", options="header"]
|===
|*Date*
|*PIC*
|*Version*
|*Description*

|25/04/2022
|Nga Le
|1.0
|Initial version.

|05/05/2022
|Nga Le
|1.1
|Update Diagram.

|===

== *System Overview*

[plantuml, "permisison_service_overview", png]
----
@startuml
title: System Overview

left to right direction

node "Permission Server" {
  node "NATS Server" <<cluster setup>> {
    [NATS Server] <<instance>> as server
  }

  node "Permision Server" {
    [Permission Service] <<https>> as as
  }

  node "Core Services" {
    [Regis Service] <<https>> as regis
  }

  database "PostgreSQL" <<shared instance>> {
    [Permission DB] <<db name>> as db
  }

  db <-right-> as
  regis -down-> as
  regis <-right-> server
}
@enduml
----

*Notes*:

- The permission server will handle user permissions.
- The user permission is used to grant access to NATS Server.

== *Account Server APIs*:

=== *Add Permission*:

==== *Endpoint API*:

- *Method*:  _POST_

- *Header*: _Authorization: Bearer JWT_TOKEN_

- *Endpoint Url*:  _https://PERMISSION_SERVICE:PORT/permission/add_

- *Payload*:

[source,json]
----
{
  "home_id": <string>,
  "user_id": <string>,
  "client_id": <string>,
}
----

- *Response*: _200_

=== *Remove Permission*:

==== *Endpoint API*:

- *Method*:  _POST_

- *Header*: _Authorization: Bearer JWT_TOKEN_

- *Endpoint Url*:  _https://PERMISSION_SERVICE:PORT/permission/remove_

- *Payload*:

[source,json]
----
{
  "home_id": <string>,
  "user_id": <string>,
  "client_id": <string>
}
----

- *Response*: _200_

=== *Get NATS Info*:

==== *Sequence Diagaram*:

[plantuml, "get_nats_info", png]
----
@startuml
autonumber
RegisService -> PermissionService: Request NATS Info.
alt Has Permission
PermissionService -> PermissionService: Generate NATS Info.
PermissionService --> RegisService: Return NATS Info.
else No Permisison
autonumber 2 1
PermissionService --> RegisService: Return Not Found.
end
@enduml
----

==== *Endpoint API*:

- *Method*:  _GET_

- *Header*: _Authorization: Bearer JWT_TOKEN_

- *Endpoint Url*:  _https://PERMISSION_SERVICE:PORT/permission/nats/info_

- *Parameters*:

[cols="1,2", options="header"]
|===
|*Key*
|*Data Type*

|user_id
|String

|home_id
|String

|client_id
|String
|===

- *Response*:

[source,json]
----
{
  "urls": [
    <nats_url_1>,
    <nats_url_2>,
    <nats_url_3>
  ],
  "creds"; <string>
}
----
