site:
  title: FW Docs
  url: /firmware-documents/1.0.0/firmware_documents.html
content:
  sources:
  - url: ./
    branches: main
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
asciidoc:
  attributes:
    sectanchors: true
    plantuml-server-url: http://www.plantuml.com/plantuml
    plantuml-fetch-diagram: true
    imagesoutdir: temp_image/
  extensions:
  - asciidoctor-plantuml